/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test public void testAppHasAGreeting() {

        gradle.App classUnderTest = new gradle.App();
        assertNotNull("app should have a greeting", ((gradle.App) classUnderTest).getGreeting());
    }
}

